### PR TITLE
Memory management (fixes #22,  closes #24)

### LINKED ISSUE #22: Zig libraries need to manage their own memory
I was looking for a diffing library to use on a Zig project, and `diffz` looked like the best candidate. Even with just the diffing portion of diff-match-patch, and a lack of recent commits (it happens), I figured hey, community-supported library, it's got the part I actually need, and maybe I could take some time to continue the port.

I was disappointed to see that the library uses an arena as though it were a garbage collector. In a ziglib, functions are expected to take a generic `Allocator`, *and behave accordingly*, by freeing any memory they don't return. If the user wants to use an `ArenaAllocator`, that's fine, `free` is a no-op unless the allocation happens to be the last one performed, so one ends up with the performance benefits, while maintaining the flexibility which is a core competency of the language.

I assume this unfortunate state of affairs came to be because this version of diff-match-patch is a port from a garbage collected language, C♯ presumably.  It's just a pity, because Zig provides such excellent tools for finding memory leaks, use after free, and double free, and the library has a robust test suite. Proper memory management could have been added during the port, and then this would be a real Zig library, not just a promising sketch of one.

Anyway, now there's an issue to track this, in case anyone wants to close it...

### LINKED ISSUE #24: Allocator-independent testing
The merge conversation in #23 has demonstrated that switching to bring-your-own-allocator memory management will require some changes in testing strategy. 

If I'm understanding some context correctly, ZLS is using `DiffMatchPatch`, and surely doing so with an arena. So for benchmarking and consistency reasons, it would be good to be able to run the tests using an arena as well. 

Furthermore, it would be good to assure that an `OutOfMemory` incident doesn't leak memory, or improperly double-free it.  `std.testing` has `FailingAllocator` for that kind of check, so that's a minimum of three allocators which would be well to use on the test suite. 

Last, it would be good to set up the tests so that they're also benchmarks, using `std.Timer` to collect data. That could be conditionally reported from a separate build step, and is harmless to run when the information it provides isn't necessary.  This could include running the tests many more times, in order to get useful amounts of timing data.

My sketch of a solution here is pretty simple: change each of the test blocks into a pair: a function, which takes an allocator and performs the tests, and a test block, which calls that function with an allocator.   The functions should initialize a Timer and return its results, that's probably the right level of granularity but we should discuss that.

How things are structured from there is less clear to me. I haven't used a failing allocator before, but it seems pretty simple: run a `for (0..) |allowed_allocations|` loop, which initializes a `FailingAllocator` to permit that many allocations, and `break` when we no longer `catch` `OutOfMemory` errors. 

Whether the tests should be run on both the `std.testing.allocator`, and an arena, every time, is less clear to me. Currently, on an M1, a test run is absolutely dominated by build time, finishing in a few hundred milliseconds when `has_side_effects = true` is used to allow the tests to rerun without any build changes. So some changes which bump the test running time up to a second or so wouldn't really move the needle in the usual workflow where tests are run after a build. 

But it isn't obvious to me that double testing with `std.testing.allocator`, and an arena, is an important thing to do every time. Another option is to add the arena as a build flag, which would comptime switch from std.testing.allocator to `ArenaAllocator`.  I also don't know what happens when you make a `FailingAllocator` backed by an `ArenaAllocator`, but the design seems pretty composable. 

So that's my sketch of a plan here, let me know what you think.

### PR DESCRIPTION
**Pull request by mnemnion**
This PR adds proper memory management to `diffz`.  

Almost all the tests are ported to use `std.testing.allocator`, and they all pass.  There's a few in the `diff` test which I didn't feel like rewriting, I would encourage one of the maintainers to do so after the merge.

### CODE REVIEW

**Comment by archaistvolts** [comment]
I haven't looked closely at this PR yet but it seems like a nice improvement at a glance.  One thing I would like to see is some kind of benchmark, perhaps just of the tests or diffing some large files.

Also would like to hear back from someone who's run zls with these changes and a debug or release safe build for a few days or so.

**Comment by mnemnion** [comment]
> One thing I would like to see is some kind of benchmark, perhaps just of the tests or diffing some large files.

A benchmark would be a valid addition to the library, but one I don't have time to write.

To be fair to the PR, the benchmark should be run against the existing library both with and without an arena used.  The PR still allows for an arena, after all, but it doesn't require it. That would separate performance regressions caused by the memory management changes, from any which are due to not using an arena (and therefore necessary to use it correctly).  Because all things being equal, it's probably faster to run most code with an arena, and free it all at the end, but this is a tradeoff for additional memory pressure, so that's not a guarantee. 

I did eliminate some unnecessary copying in the process of switching over to valid use of any allocator, so it's possible that the code is faster both with an arena and without. I look forward to your conclusions.

**Comment by archaistvolts** [comment]
> A benchmark would be a valid addition to the library, but one I don't have time to write.

How about just measuring the runtime of the tests before and after this PR?  You could just modify build.zig to install the tests and run `$ time zig-out/bin/tests` to get a ballpark.  And for more details copy the before and after test binaries somewhere and use something like hyperfine or poop to measure.  

I agree with what you said about the existing code having an advantage.  Seems like using an arena both before and after might be the closest to a fair comparison since free/destroy for arenas is a no-op afaik.

I think that having some kind timings would go a long way to inspire confidence in these changes.

Also if you use zls: build it with this PR in release safe and try running it for a few days or more and report back if you notice anything unusual?

**Comment by mnemnion** [comment]
> How about just measuring the runtime of the tests before and after this PR?

That's more straightforward, yes.  It's a bit tricky to set up so that the tests can be run with either an arena or not, but taking a baseline is very simple. 

"bit tricky" meaning readily achievable with comptime and a conditional defer on deinitializing the test allocator, also moving it to a global. But just running an A/B test with the branches and system `time` is easy. Will let you know.

**Comment by mnemnion** [comment]
Original branch:

```
Executed in  177.64 millis    fish           external
   usr time  133.54 millis    0.05 millis  133.49 millis
   sys time   34.21 millis    1.77 millis   32.43 millis
```
New branch using testing allocator:

```
Executed in  204.25 millis    fish           external
   usr time  151.01 millis    0.04 millis  150.97 millis
   sys time   45.58 millis    1.26 millis   44.31 millis
```
So in Debug mode, 1.15X slower.

But! That's in safety-mode, when the testing allocator doesn't actually release memory, and does comprehensive checks to prevent leaks and report use-after-free and double-free.

Something interesting happens when we switch to `-Doptimize=ReleaseFast`, here's the original:

```
________________________________________________________
Executed in  177.07 millis    fish           external
   usr time  132.75 millis    0.05 millis  132.69 millis
   sys time   36.29 millis    1.86 millis   34.44 millis
```
Which barely changes, and here's the `memory-management` branch:

```
________________________________________________________
Executed in  166.93 millis    fish           external
   usr time  127.30 millis    0.04 millis  127.26 millis
   sys time   32.20 millis    1.24 millis   30.96 millis
```
So in release mode, the original arena code is 1.06X slower than the memory management branch, a negative regression of 94%, 6% faster, I never know which framing of these numbers someone is accustomed to. This is readily interpreted: almost all allocations are u8, so the allocator has a lot of flexibility for reusing recently-freed memory.   

Also bear in mind that the tests are inherently doing more work, since all Diff strings except the comparison ones have to be duped so that freeing them doesn't segfault, so the practical savings are possibly greater than this quick check shows. 

Worth emphasizing that the short duration makes these numbers pretty fuzzy, and more and larger tests with some built-in benchmarking would be a useful addition. I also think it's worthwhile to set the tests up so the allocator can be swapped, if I find some time I might do that part. 

But as a preliminary, it looks like the changes have a minimal effect on performance, and a positive one where it counts. 

Perhaps worth noting: I ran each of the four tests three times and chose the middle value, as a cheap way to reduce bias, and also so that I'd spot it if there were large differences between runs. The difference were always under ten milliseconds.

**Comment by archaistvolts** [comment]
Thanks!  One thing to consider, [zls install notes](https://github.com/zigtools/zls?tab=readme-ov-file#from-source) do recommend using release safe build.  So that might be the most important build mode to consider.

> Also bear in mind that the tests are inherently doing more work, since all Diff strings except the comparison ones have to be duped so that freeing them doesn't segfault.

Oh thats right.  I forgot about this.  Maybe benching the tests isn't a good measurement because of this added work.  My apologies if thats the case.

Perhaps @SuperAuguste or @Techatrix or someone else might propose a better way for us to benchmark these changes from zls.  Is there any existing way to benchmark zls we should be using here?  If not perhaps a better benchmark might be to just time zls tests?  I can't remember if all zls' tests use the same allocation strat as in main.

Also please let us know these benchmarks are even necessary.  I don't want to be making unnecessary work for anyone.

**Comment by mnemnion** [comment]
I'm afraid I don't see what role zls plays here. To be clear, that's not a disagreement, I literally don't know what part zls can play in testing this. 

But (easily done) middle-of-three for ReleaseSafe for the `main` branch:

```
________________________________________________________
Executed in  171.26 millis    fish           external
   usr time  129.24 millis    0.06 millis  129.18 millis
   sys time   31.87 millis    1.83 millis   30.04 millis
```

and for `memory-management`:

```
________________________________________________________
Executed in  174.95 millis    fish           external
   usr time  130.14 millis    0.04 millis  130.10 millis
   sys time   34.81 millis    2.07 millis   32.74 millis
```
That's within the margin of error where it's pure luck which one completed quicker. I think the important part here is that there are no observable performance regressions with the data I can easily generate.

If anyone would like to add more test data, or set up some timing from within the test itself, I would be happy to merge that and run it as well.

**Comment by Techatrix** [comment]
I was interested to see if there where any differences in memory usage so I did some benchmarks myself.
All runs are in ReleaseFast with `check_lines == true`.

<details>

<summary>diff Sema.zig & Sema.zig (100 times per run)</summary>

```bash
[nix-shell:~/repos/diffz]$ poop -d 10000 ./bench1-old-arena-fast ./bench1-new-arena-fast ./bench1-new-gpa-fast
Benchmark 1 (190 runs): ./bench1-old-arena-fast
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          52.0ms ±  324us    50.8ms … 53.1ms         12 ( 6%)        0%
  peak_rss           3.37MB ± 15.8KB    3.32MB … 3.39MB         16 ( 8%)        0%
  cpu_cycles         45.5M  ±  317K     44.9M  … 46.7M           2 ( 1%)        0%
  instructions       14.1M  ± 2.06K     14.1M  … 14.1M          17 ( 9%)        0%
  cache_references   1.22M  ± 24.5K     1.15M  … 1.25M          17 ( 9%)        0%
  cache_misses       2.54K  ± 1.99K      762   … 15.4K          21 (11%)        0%
  branch_misses       695   ± 42.7       589   …  918            7 ( 4%)        0%
Benchmark 2 (191 runs): ./bench1-new-arena-fast
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          51.9ms ±  334us    51.3ms … 53.2ms          9 ( 5%)          -  0.3% ±  0.1%
  peak_rss           3.50MB ± 17.3KB    3.46MB … 3.58MB         19 (10%)        💩+  3.9% ±  0.1%
  cpu_cycles         45.5M  ±  360K     44.9M  … 47.1M           5 ( 3%)          -  0.1% ±  0.1%
  instructions       14.1M  ± 2.14K     14.1M  … 14.1M          18 ( 9%)          +  0.0% ±  0.0%
  cache_references   1.22M  ± 19.3K     1.14M  … 1.26M           7 ( 4%)          +  0.2% ±  0.4%
  cache_misses       1.99K  ± 1.78K      656   … 20.2K          15 ( 8%)        ⚡- 21.6% ± 14.9%
  branch_misses       629   ± 43.7       540   …  749            4 ( 2%)        ⚡-  9.4% ±  1.2%
Benchmark 3 (186 runs): ./bench1-new-gpa-fast
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          53.1ms ±  273us    52.6ms … 54.1ms          7 ( 4%)        💩+  2.0% ±  0.1%
  peak_rss           3.50MB ± 21.9KB    3.47MB … 3.61MB          1 ( 1%)        💩+  3.9% ±  0.1%
  cpu_cycles         45.7M  ±  403K     45.0M  … 47.3M           9 ( 5%)          +  0.3% ±  0.2%
  instructions       14.1M  ± 1.81K     14.1M  … 14.1M          14 ( 8%)          +  0.2% ±  0.0%
  cache_references   1.22M  ± 12.8K     1.14M  … 1.25M           5 ( 3%)          +  0.1% ±  0.3%
  cache_misses       3.13K  ± 1.93K     1.34K  … 20.0K          11 ( 6%)        💩+ 23.0% ± 15.6%
  branch_misses       868   ± 78.7       611   … 1.10K           6 ( 3%)        💩+ 25.0% ±  1.8%
```

</details>

<details>

<summary>diff Sema.zig & AstGen.zig</summary>

```bash
[nix-shell:~/repos/diffz]$ poop -d 10000 ./bench2-old-arena-fast ./bench2-new-arena-fast ./bench2-new-gpa-fast
Benchmark 1 (10 runs): ./bench2-old-arena-fast
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          1.01s  ±  387us    1.01s  … 1.01s           0 ( 0%)        0%
  peak_rss           58.8MB ± 63.3KB    58.7MB … 58.9MB          0 ( 0%)        0%
  cpu_cycles         3.83G  ± 8.37M     3.82G  … 3.84G           0 ( 0%)        0%
  instructions       10.2G  ± 48.3M     10.1G  … 10.2G           0 ( 0%)        0%
  cache_references   2.84M  ± 64.2K     2.75M  … 2.92M           0 ( 0%)        0%
  cache_misses       68.8K  ± 23.5K     54.6K  …  123K           0 ( 0%)        0%
  branch_misses      50.4M  ±  135K     50.3M  … 50.7M           0 ( 0%)        0%
Benchmark 2 (10 runs): ./bench2-new-arena-fast
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          1.01s  ±  422us    1.01s  … 1.01s           0 ( 0%)          -  0.0% ±  0.0%
  peak_rss           58.8MB ± 67.7KB    58.7MB … 58.9MB          0 ( 0%)          -  0.0% ±  0.1%
  cpu_cycles         3.83G  ± 10.5M     3.82G  … 3.84G           0 ( 0%)          -  0.0% ±  0.2%
  instructions       10.2G  ± 62.8M     10.1G  … 10.3G           0 ( 0%)          +  0.2% ±  0.5%
  cache_references   2.84M  ± 62.9K     2.73M  … 2.95M           0 ( 0%)          +  0.0% ±  2.1%
  cache_misses       65.0K  ± 26.4K     52.1K  …  139K           1 (10%)          -  5.5% ± 34.1%
  branch_misses      50.5M  ±  205K     50.1M  … 50.8M           0 ( 0%)          +  0.1% ±  0.3%
Benchmark 3 (10 runs): ./bench2-new-gpa-fast
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          1.01s  ±  370us    1.01s  … 1.01s           0 ( 0%)          -  0.1% ±  0.0%
  peak_rss           41.7MB ± 41.9KB    41.6MB … 41.7MB          1 (10%)        ⚡- 29.1% ±  0.1%
  cpu_cycles         3.84G  ± 1.96M     3.83G  … 3.84G           0 ( 0%)          +  0.1% ±  0.1%
  instructions       9.97G  ±  171M     9.50G  … 10.1G           1 (10%)          -  1.8% ±  1.2%
  cache_references   2.61M  ± 58.3K     2.48M  … 2.69M           0 ( 0%)        ⚡-  7.8% ±  2.0%
  cache_misses       56.3K  ± 8.48K     49.7K  … 78.8K           1 (10%)          - 18.1% ± 24.1%
  branch_misses      50.4M  ± 1.02M     47.5M  … 51.0M           1 (10%)          -  0.1% ±  1.4%
```

</details>

<details>

<summary>diff Sema.zig & Sema2.zig (100 times per run)</summary>

`Sema2.zig` is identical to `Sema.zig` except that I have added two new lines somewhere in the middle of the document.

```bash
[nix-shell:~/repos/diffz]$ poop -d 10000 ./bench3-old-arena-fast ./bench3-new-arena-fast ./bench3-new-gpa-fast
Benchmark 1 (70 runs): ./bench3-old-arena-fast
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           143ms ±  642us     142ms …  145ms          0 ( 0%)        0%
  peak_rss           5.90MB ± 6.38KB    5.90MB … 5.92MB          0 ( 0%)        0%
  cpu_cycles          313M  ±  848K      312M  …  315M           0 ( 0%)        0%
  instructions        997M  ± 2.00K      997M  …  997M           3 ( 4%)        0%
  cache_references   1.56M  ± 22.5K     1.46M  … 1.59M           2 ( 3%)        0%
  cache_misses       43.3K  ± 6.13K     32.2K  … 57.1K           0 ( 0%)        0%
  branch_misses      2.68K  ±  155      2.10K  … 2.97K           1 ( 1%)        0%
Benchmark 2 (70 runs): ./bench3-new-arena-fast
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           143ms ±  653us     142ms …  145ms          2 ( 3%)          -  0.1% ±  0.2%
  peak_rss           5.90MB ± 7.43KB    5.90MB … 5.93MB          0 ( 0%)          +  0.0% ±  0.0%
  cpu_cycles          313M  ±  737K      312M  …  315M           2 ( 3%)          -  0.1% ±  0.1%
  instructions        997M  ± 2.96K      997M  …  997M           4 ( 6%)          +  0.0% ±  0.0%
  cache_references   1.50M  ± 12.6K     1.45M  … 1.53M           3 ( 4%)        ⚡-  4.0% ±  0.4%
  cache_misses       37.0K  ± 6.94K     20.6K  … 53.8K           0 ( 0%)        ⚡- 14.4% ±  5.0%
  branch_misses      2.17K  ±  152      1.83K  … 2.46K           0 ( 0%)        ⚡- 19.0% ±  1.9%
Benchmark 3 (71 runs): ./bench3-new-gpa-fast
  measurement          mean ± σ            min … max           outliers         delta
  wall_time           142ms ±  616us     140ms …  144ms          2 ( 3%)          -  1.0% ±  0.1%
  peak_rss           5.91MB ± 7.77KB    5.90MB … 5.93MB          0 ( 0%)          +  0.0% ±  0.0%
  cpu_cycles          303M  ± 1.03M      302M  …  308M           3 ( 4%)        ⚡-  3.2% ±  0.1%
  instructions        997M  ± 5.43K      997M  …  997M           6 ( 8%)          +  0.0% ±  0.0%
  cache_references   1.62M  ± 31.9K     1.54M  … 1.67M           0 ( 0%)        💩+  3.7% ±  0.6%
  cache_misses       49.0K  ± 22.9K     13.1K  … 81.8K           0 ( 0%)          + 13.3% ± 12.8%
  branch_misses      3.20K  ±  258      2.33K  … 3.71K           4 ( 6%)        💩+ 19.7% ±  2.6%
```

</details>

There isn't much of an impact to wall time but there is a nice reduction on peak RSS in the Sema.zig vs. AstGen.zig run.
I assume that ZLS's diffs are most similar to the third benchmark so it won't be noticeably affected by these changes.

File: build.zig.zon [hunk 1]
```diff
@@ -0,0 +1,13 @@
+.{
+    .name = "diffz",
+    .version = "0.0.1",
+    .paths = .{
+        "DiffMatchPatch.zig",
+        ".gitattributes",
+        ".gitignore",
```
Comment (Techatrix) [inline build.zig.zon]: The Zig package manager doesn't care about the version control system being used. The `paths` field itself specifies what files should be included and which not.
```suggestion
```

File: build.zig [hunk 2]
```diff
@@ -1,7 +1,35 @@
...
+        .name = "diffz",
+        .root_source_file = b.path("DiffMatchPatch.zig"),
+        .target = target,
+        .optimize = optimize,
+    });
+
+    // This declares intent for the library to be installed into the standard
+    // location when the user invokes the "install" step (the default step when
+    // running `zig build`).
+    b.installArtifact(lib);
```
Comment (Techatrix) [inline build.zig]: `DiffMatchPatch.zig` doesn't export any symbols which makes the generated library empty and useless.
```suggestion
```
Providing a C API for this project could be added at some point.

File: .gitignore [hunk 3]
```diff
@@ -1 +1,2 @@
-zig-cache
+zig-*
+.zig-*
```
Comment (Techatrix) [inline .gitignore]: Let's be more explicit:
```suggestion
.zig-cache
zig-cache
zig-out
```

File: DiffMatchPatch.zig [hunk 4]
```diff
@@ -1909,49 +2079,61 @@ fn rebuildtexts(allocator: std.mem.Allocator, diffs: DiffList) ![2][]const u8 {
...
-    try testing.expectEqualDeep(diffs, try this.diffBisect(arena.allocator(), a, b, 0)); // Timeout.
+    var diff_bisect2 = try this.diffBisect(allocator, a, b, 0);
+    defer deinitDiffList(allocator, &diff_bisect2);
+    try testing.expectEqualDeep(diffs2, diff_bisect2); // Timeout.
 }
 
 const talloc = testing.allocator;
+
 test diff {
     var arena = std.heap.ArenaAllocator.init(talloc);
```
Comment (Techatrix) [inline DiffMatchPatch.zig]: Is it intentional that an arena allocator is being used here?

File: DiffMatchPatch.zig [hunk 5]
```diff
@@ -2,9 +2,34 @@ const DiffMatchPatch = @This();
...
 const DiffList = ArrayListUnmanaged(Diff);
 
+/// Deinit an `ArrayListUnmanaged(Diff)` and the allocated slices of
+/// text in each `Diff`.
+pub fn deinitDiffList(allocator: Allocator, diffs: *DiffList) void {
+    defer diffs.deinit(allocator);
+    for (diffs.items) |d| {
+        if (d.text.len > 0) {
+            allocator.free(d.text);
+        }
```
Comment (Techatrix) [inline DiffMatchPatch.zig]: The free function is a no-op if the length is zero.
```suggestion
        allocator.free(d.text);
```

**Review by Techatrix — CHANGES_REQUESTED** [review]
I see a lot of potential leaks on out of memory in the code. Let me demonstrate it based on this line.

```zig
try diffs.append(allocator, Diff.init(.delete, try allocator.dupe(u8, before)));
try diffs.append(allocator, Diff.init(.insert, try allocator.dupe(u8, after)));
```

If `diffs.append` fails then the previously duped memory is leaked. This can be corrected like this:

```zig
try diffs.ensureUnusedCapacity(allocator, 2);
diffs.appendAssumeCapacity(try allocator.dupe(u8, before));
diffs.appendAssumeCapacity(try allocator.dupe(u8, after));
```

The standard library provides a very useful utility called `std.testing.checkAllAllocationFailures` that runs a user provided function multiple times and inserts an artificial out of memory error on every callsite and checks if no memory leak occurred. This would have reported the possible leak in the example above. This could all be bundled into a helper function to make the unit tests cleaner.

File: DiffMatchPatch.zig (hunk 4 above)
Comment (Techatrix) [reply DiffMatchPatch.zig]: Oh, I overlooked your comment about these tests. I could take care of that if you'd like. Would be a good opportunity to make use of `std.testing.checkAllAllocationFailures`. See https://github.com/ziglibs/diffz/pull/23#pullrequestreview-2161842930

Comment (mnemnion) [reply DiffMatchPatch.zig]: Rewriting all the tests to use the testing allocator was a lot of the work in this patch, as you can see from the diffs. The ones in `test diff {` aren't as amenable to the multi-cursor approach I was taking, so I rewrote the more complex ones, but not all of them.

**Comment by mnemnion** [comment]
> I assume that ZLS's diffs

Ah! So this library is used in ZLS. Thanks, that was the missing context for me about why it was mentioned.

File: .gitignore (hunk 3 above)
Comment (mnemnion) [reply .gitignore]: Reasonable choice, I thought of it as a bit of future-proofing in case Zig grows another Zig directory, but it's trivial to add it to `.gitignore`s if that happens.

File: build.zig.zon (hunk 1 above)
Comment (mnemnion) [reply build.zig.zon]: Are you sure? The standard template for `build.zig.zon` says this: 

```
        // This makes *all* files, recursively, included in this package. It is generally
        // better to explicitly list the files and directories instead, to insure that
        // fetching from tarballs, file system paths, and version control all result
        // in the same contents hash.
```

The contents hash is calculated from the files listed in `zig.build.zon`, and I've found that leaving out files means that another package can't actually find the dependency.  I think these file names should be left in, and then removed if some integration testing shows that they don't have to be included.

**Comment by mnemnion** [comment]
> I see a lot of potential leaks on out of memory in the code. Let me demonstrate it based on this line.

That's a good catch. There's a lot of that in the code, I'll add a helper function which does "append with dupe" correctly, that will prevent this problem by construction and make the code less verbose as well.

File: build.zig.zon (hunk 1 above)
Comment (Techatrix) [reply build.zig.zon]: I am specifically talking about `.gitattributes` and `.gitignore`. A projects that dependents on this diffz project has not use for these files. This would also apply if there were a `tests` subdirectory. If you were to leave out the `build.zig` then obviously the package wouldn't work as dependency but I am just talking about these two files.

**Comment by Techatrix** [comment]
> I'll add a helper function which does "append with dupe" correctly, that will prevent this problem by construction and make the code less verbose as well.

Are you trying to add a function that is similar to this one?

```zig
fn appendDiff(allocator: std.mem.Allocator, diffs: DiffList, operation: Diff.Operation, text: []const u8) std.mem.Allocator.Error!void {
    try diffs.ensureUnusedCapacity(allocator, 1);
    diffs.appendAssumeCapacity(Diff.init(operation, try allocator.dupe(u8, text)));
}
```

If that is the case, then I would suggest against that. In some cases you may append multiple diffs. Sometimes even with `appendSlice`. It is best to do one call to `ensureUnusedCapacity` and then only call the `AssumeCapacity` variants. This is harder to achieve when you try to simplify things by adding a helper function just to avoid having to typing that extra line.

For the tests you can do something like this:
```zig
var diffs = try DiffList.initCapacity(alloc, 4);
defer deinitDiffList(alloc, &diffs);
diffs.appendAssumeCapacity(Diff.init(.delete, try alloc.dupe(u8, "ab")));
diffs.appendAssumeCapacity(Diff.init(.insert, try alloc.dupe(u8, "cd")));
diffs.appendAssumeCapacity(Diff.init(.equal, try alloc.dupe(u8, "12")));
diffs.appendAssumeCapacity(Diff.init(.delete, try alloc.dupe(u8, "e")));
```

**Comment by mnemnion** [comment]
I think this latest change does handle memory correctly, by using `errdefer` for cleanup when allocation failure could cause leaks. 

It's probably not complete. Setting up the test suite to do memory failing checks is going to be necessary here, there are edge cases to consider like accidentally having multiple `errdefer` calls on the same memory, which would double-free. 

I didn't end up using the `ensureUnusedCapacity` `appendAssumeCapacity` pairs, but the result should be correct nonetheless. Let me know what you think.

**Comment by mnemnion** [comment]
> *Sometimes even with appendSlice*

I was working on the change and didn't see this comment. I'll check those cases as well, some of them are borrows and I mostly handled that with an `errdefer` on the original owner. The issue being that deinitializing a `DiffList` using `diffs.deinit(allocator)` won't free the memory of the text, I added a couple helper functions already to handle that for removes and deinits. 

I tried turning the `DiffList` into a custom struct so that the helper functions could be methods, but realized that changing the way the library functions was probably a bad idea, and that at least it should be done separately from the memory work.

**Comment by mnemnion** [comment]
There were, in fact, two more places where an `errdefer` was needed, involving `appendSlice`. `ensureCapacity` wouldn't help here because it still wouldn't free the `Diff` texts.

To clarify something, the intention behind writing `diffsAppend` and `diffsInsert` isn't to save typing.  It's to make sure that the correct thing is done in every case. If there's a raw use of `diffs.append` with a `dupe` in it, that's a bug.  Making the code cleaner, and therefore easier to understand, is a nice bonus, and something which often follows from that sort of choice.

**Comment by Techatrix** [comment]
Here is a patch that should cleanup most of the tests: [file](https://github.com/user-attachments/files/16119787/Patch.txt)
`git apply ...` should do the trick.

**Comment by Techatrix** [comment]
> To clarify something, the intention behind writing `diffsAppend` and `diffsInsert` isn't to save typing. It's to make sure that the correct thing is done in every case. If there's a raw use of `diffs.append` with a `dupe` in it, that's a bug. Making the code cleaner, and therefore easier to understand, is a nice bonus, and something which often follows from that sort of choice

Sure, using `append` with `dupe` is a bug.
```zig
var diffs: DiffList = .{};
defer deinitDiffList(alloc, &diffs);
try diffs.append(alloc, Diff.init(.delete, try alloc.dupe(u8, "ab")));
try diffs.append(alloc, Diff.init(.insert, try alloc.dupe(u8, "cd")));
try diffs.append(alloc, Diff.init(.equal, try alloc.dupe(u8, "12")));
try diffs.append(alloc, Diff.init(.delete, try alloc.dupe(u8, "e")));
```
But this is what I am suggesting https://github.com/ziglibs/diffz/pull/23#pullrequestreview-2161842930
```zig
var diffs: DiffList = .{};
defer deinitDiffList(alloc, &diffs);
try diffs.ensureUnusedCapacity(alloc, 4);
diffs.appendAssumeCapacity(Diff.init(.delete, try alloc.dupe(u8, "ab")));
diffs.appendAssumeCapacity(Diff.init(.insert, try alloc.dupe(u8, "cd")));
diffs.appendAssumeCapacity(Diff.init(.equal, try alloc.dupe(u8, "12")));
diffs.appendAssumeCapacity(Diff.init(.delete, try alloc.dupe(u8, "e")));
```
or
```zig
var diffs = try DiffList.initCapacity(alloc, 4);
defer deinitDiffList(alloc, &diffs);
diffs.appendAssumeCapacity(Diff.init(.delete, try alloc.dupe(u8, "ab")));
diffs.appendAssumeCapacity(Diff.init(.insert, try alloc.dupe(u8, "cd")));
diffs.appendAssumeCapacity(Diff.init(.equal, try alloc.dupe(u8, "12")));
diffs.appendAssumeCapacity(Diff.init(.delete, try alloc.dupe(u8, "e")));
```

The reason why I am suggesting this over the helper function:
```zig
fn diffsAppend(allocator: Allocator, diffs: *DiffList, op: Diff.Operation, text: []const u8) !void {
    const new_text = try allocator.dupe(u8, text);
    errdefer allocator.free(new_text);
    try diffs.append(allocator, Diff{ .operation = op, .text = new_text });
}
```
is because there it avoids the `allocator.free(new_text);` and appending multiple times with the helper function has to check the capacity of the array list on every append. If you already reserved the capacity then no `errdefer` is necessary and the capacity of the array list will only need to be checked once. This generates better assembly while maintaining good readability.

**Comment by mnemnion** [comment]
> appending multiple times with the helper function has to check the capacity of the array list

Which, to be fair, the original code was already doing. 

But you raise a fair point, albeit one I wish I'd seen before I committed the first fix. 

I'll try and find some time in the afternoon to change over to using that pattern instead.

**Comment by mnemnion** [comment]
> Here is a patch that should cleanup most of the tests

Ironically, applying the patch was a bit wonky, but amenable to cleanup. Might want to eyeball the result or do a log compare to make sure it looks like you intended it to. 

I'm going to open up an issue on making further changes to the tests, so that thinks like allocation failure can be tested as well.

File: build.zig.zon (hunk 1 above)
Comment (mnemnion) [reply build.zig.zon]: Right, but if you take a tarball using `zig fetch --save`, then empirically, the build system won't successfully link to the dependency, because the hash it generates will be wrong.  I've seen this happen setting up another library to use `build.zig.zon`. 

So while I see your point about not having any use for those files, I think they need to stay for the current iteration of the build system to work successfully.  

It's worth checking this after the PR, I suppose. If I'm wrong, and the build failures I was seeing aren't actually correlated with my including files I didn't think needed to be included, it's very easy to remove them.

**Comment by Techatrix** [comment]
I have wrapper most of the tests in `testing.checkAllAllocationFailures` in https://github.com/Techatrix/diffz/commit/34d3a7b8ec3edd19865dbb7438aa2a371c0dded4 and most of the tests report some kind of memory error. Just search for `if (true) return error.SkipZigTest; // TODO`

File: build.zig.zon (hunk 1 above)
Comment (Techatrix) [reply build.zig.zon]: tbh I have no clue what any of this has to do with the removal of `.gitattributes` and `.gitignore` from `paths`? Whatever issue you are trying to describe is unrelated to what I am talking about.

Here are some package that don't include these two files but still work:
- https://github.com/ziglibs/known-folders/blob/master/build.zig.zon
- https://github.com/zigtools/zig-lsp-codegen/blob/main/build.zig.zon
- https://github.com/hexops/mach/blob/main/build.zig.zon
- https://github.com/zigzap/zap/blob/master/build.zig.zon

**Comment by mnemnion** [comment]
> most of the tests report some kind of memory error.

That is expected at this point. 

I'll make a fork on my repo, `memory-management-staging`, that's identical to the PR. That way you can open up a PR from your branch, I can merge it, fix the errors, and push them onto this branch.

**Comment by Techatrix** [comment]
https://github.com/mnemnion/diffz/pull/1

**Comment by mnemnion** [comment]
So there's a design conflict here, because a) definitely found that I wasn't errdeferring halfmatches, but the next one I hit at line 1787 is because of the diffs, which are passed in.

The problem is that inside of `diffCharsToLines`, we *should not* errdefer the diffs, which are already `errdefer`ed in `diffLineMode`, which is a public function.  So if I double errdefer, it segfaults from a double-free. 

So I think what has to happen is that exhaustive allocation failure checks have to come through the public functions only.  Those are the only ones which can be called in actual use, so if they free memory correctly, it's fine. 

I misread what you said and though there was one `SkipZigTest` line, so I absentmindedly merged and pushed the staging branch. But I'll go ahead and do a hard reset on this branch and a force push.  I'll keep an eye out for the next PR.

**Comment by mnemnion** [comment]
So the internal tests are fine, actually, as long as the data is properly prepared. 

So I've fixed all the leaks in the tests, and wrapped tests which segfault because they try to free `.rodata` strings in `if (false)` blocks tagged `TODO #23`.  I also included a helper function `sliceToDiffList` which will make converting those tests relatively painless.

**Comment by mnemnion** [comment]
That should be all of it. 

I realized in writing some tests for `rebuildtexts` that the new testing functions were, in fact, making copies of the string data. Apparently a double-free during error conditions does not get caught be the allocator, but just segfaults, which I had come to associate with trying to free `.rodata`, so false positive there.

File: DiffMatchPatch.zig [hunk 6]
```diff
@@ -96,10 +129,15 @@ fn diffInternal(
...
     if (std.mem.eql(u8, before, after)) {
+        var diffs = DiffList{};
+        errdefer deinitDiffList(allocator, &diffs);
         if (before.len != 0) {
-            try diffs.append(allocator, Diff.init(.equal, try allocator.dupe(u8, before)));
+            try diffs.ensureUnusedCapacity(allocator, 1);
+            diffs.appendAssumeCapacity(Diff.init(
+                .equal,
+                try allocator.dupe(u8, before),
+            ));
```
Comment (archaistvolts) [inline DiffMatchPatch.zig:143]: Just a minor style suggestion, but when appending 1 item, I prefer to use `append()`.  `ensureTotalCapacity() + appendAssumeCapacity()` is just more verbose and does the same thing as `append()`.

Please ignore me if this was already mentioned or counter to @Techatrix reviews.  I have been following this thread but may have missed some of it.

Comment (mnemnion) [reply DiffMatchPatch.zig:143]: 😅 There was a whole discussion, it's gone because of the changes.

The problem, which @Techatrix identified, is that just using `append()` means that the duped text leaks if the append fails. He graciously reworked the tests to catch all `OutOfMemory` errors, and status quo is that I've fixed the leaks and double-frees that revealed. 

It was a real learning experience for me, an eye-opener. I'm experienced with C, but Zig' execution model (because of defers, and how errors work) is actually quite different! Making sure that every sequence between any `try` expression has a correct memory policy is a whole different lens through which to view the code.

Comment (archaistvolts) [reply DiffMatchPatch.zig:143]: My suggestion was to use `append()` instead _only_ when there is a single `append()`.  I did see Techatrix's advice on using `ensureTotalCapacity() + appendAssumeCapacity()`.  But afaik that only made sense when there were 2 or more appends.

Comment (mnemnion) [reply DiffMatchPatch.zig:143]: Nope, you still need to separate them. It's because `appendAssumeCapacity` doesn't use a `try`, so it can't fail. The pattern isn't an efficiency thing (using it for several inserts/appends is more efficient though), it's a memory safety thing.

What this avoids: the `try allocator.dupe` succeeds, but the `try append`  fails. That means the new `[]const u8` doesn't have anywhere to live, so it leaks. 

I considered rewriting `diffAppend` and `diffInsert` to be inline and do the `ensureUnused`/`AssumeCapacity` dance where we don't have to look at it. But I figured that could be interpreted as stylistic bickering, and I'm more interested in landing the patch than on resolving a difference like that.

And I'm glad I didn't. There are a number of hairy spots in the code where those two operations have to be ordered in a way where something else comes between them.

Comment (mnemnion) [reply DiffMatchPatch.zig:143]: As an aside, I feel that the standard library could be improved by replacing every use of `Capacity` with `Space`. I don't see how that could be taken ambiguously, and it makes the calls three letters, and two syllables, shorter. 

The difference isn't huge, but every column of width comes at a premium cost.  In the meantime, I'm willing to pay the price of verbosity for the reward of robust code.

**Comment by mnemnion** [comment]
I added test coverage for `diffMatchEfficiency`, cleaning up the bugs in the process, so that's decent (not line-for-line complete) coverage of the library in its present state.

**Comment by mnemnion** [comment]
Coverage is good, at 97.5%. 

It looks like missing coverage is related to `diffLineMode` only, which isn't exercising the inside of the `halfMatch` code. Maybe worth circling back to. 

If you have `kcov` installed you can now run `zig build cov` to get a coverage report. The output directory is in the `.gitignore`.

**Comment by mnemnion** [comment]
I believe this is complete, although I'm willing to tweak it a bit here and there. 

So I wanted to bring this comment to the front:

> Also would like to hear back from someone who's run zls with these changes and a debug or release safe build for a few days or so.

It seems like a reasonable approach here is to ping the ZLS maintainers, and ask them to run with the branch themselves. I've never built it, and am not in a position to diagnose problems which might arise, unless they're definitely in the DiffMatchPatch code (but triaging that is beyond me). 

Clearly an important use case for this library, so doing some stress tests / integration is important there.

File: build.zig.zon (hunk 1 above)
Comment (mnemnion) [reply build.zig.zon]: My stance on this is fairly simple: I wrote the `build.zig.zon` file in question, and I've applied it, by using `zig fetch --save` and building a program with it. 

The two file names you want to remove from the path, I specifically added, to get that to work. It's possible that I made other changes to the code and it's a coincidence, that's not how I remember it though.

The `build.zig.zon` file is new, so there's no risk of compatibility problems with an old file which didn't have it. If *you* can confirm that removing those file names still results in a working build, that's great, it's trivial to remove them. 

But I think that's how this should happen, if it does happen. Because I know for a fact that it's functional in its current state.

Comment (mnemnion) [reply build.zig.zon]: > Whatever issue you are trying to describe is unrelated to what I am talking about.

I'll clarify: specifically, when fetching a `.tar.gz` from a release tag, if the tarball has different files from the `zig.build.zon` spec, the hash was wrong. I don't know whether or not that's true for fetching from a repo root directly, but it's important to support both cases, since `zig fetch` can do both of those things.  

I am happy to be wrong about that, but what I won't do is put additional time into confirming that those two path names have to be where they are. If you determine that isn't true, great, I have no qualms about removing them.

Comment (mnemnion) [reply build.zig.zon]: btw, if you do a git blame on that file, you'll see that those two lines were added at a different time from the rest.

File: DiffMatchPatch.zig (hunk 6 above)
Comment (archaistvolts) [reply DiffMatchPatch.zig:143]: > What this avoids: the `try allocator.dupe` succeeds, but the `try append` fails. That means the new `[]const u8` doesn't have anywhere to live, so it leaks.

Ah!  Got it now.  Thanks for clearing this up for me.  I wasn't considering an orphaned dupe().

**Comment by archaistvolts** [comment]
> It seems like a reasonable approach here is to ping the ZLS maintainers, and ask them to run with the branch themselves. I've never built it, and am not in a position to diagnose problems which might arise, unless they're definitely in the DiffMatchPatch code (but triaging that is beyond me).

I am now test driving a release safe build of zls with these changes.  Building was as simple checking out this pr and changing the diffz dep:
```diff
diff --git a/build.zig.zon b/build.zig.zon
index 6cfb176..d697252 100644
--- a/build.zig.zon
+++ b/build.zig.zon
@@ -15,9 +15,12 @@
             .url = "https://github.com/ziglibs/known-folders/archive/47076c6b11214a218e9244471d8762310820911a.tar.gz",
             .hash = "12209d2738a2e1dbd3781c2e5f01a2ea877dcfeea53efdfa1913247297d328e6b207",
         },
         .diffz = .{
-            .url = "https://github.com/ziglibs/diffz/archive/ef45c00d655e5e40faf35afbbde81a1fa5ed7ffb.tar.gz",
-            .hash = "1220102cb2c669d82184fb1dc5380193d37d68b54e8d75b76b2d155b9af7d7e2e76d",
+            .path = "../diffz",
         },
     },
     .paths = .{""},
```
Then build.
```console
~/.../zig/zls $ zig build -Doptimize=ReleaseSafe
```
If you've never built zls, not sure but I think the only other change would be to config your editor's zls path.

**Comment by mnemnion** [comment]
Note that I found a leaking test case, so this is on hold while I track that down. 

It only leaks memory in exhaustive allocation failure testing (that is, it passes a 'normal' test), so you're unlikely to see it in ZLS.

**Comment by mnemnion** [comment]
Alright, that's sorted.  

Worth noting, that this:

> It looks like missing coverage is related to diffLineMode only, which isn't exercising the inside of the halfMatch code. Maybe worth circling back to.

Is where the leaks were: in the code without coverage. I described it incorrectly, though, it was in the `diffCompute` path which uses a half match. 

Coverage now stands at 99.2%, and suggests that `diffLineMode` doesn't have comprehensive leak checks yet (because the `errdefer`s in that section of the code are not triggered by the test. Total line coverage is essential for this kind of code.

File: build.zig.zon (hunk 1 above)
Comment (Techatrix) [reply build.zig.zon]: > The two file names you want to remove from the path, I specifically added, to get that to work. It's possible that I made other changes to the code and it's a coincidence, that's not how I remember it though.

Could elaborate on that. What issue were you experiencing? I am very confused that you somehow had to add these files to `paths` in `build.zig.zon` to resolve it.

Were you for example failing to build a project that depends on 4792861d6d423f6a8fead9db6c7f0b0024b22136? (latest commit before you messed with `build.zig.zon`)

> If _you_ can confirm that removing those file names still results in a working build, that's great, it's trivial to remove them.

Just try this out! Create a new project with these three files and tell me if it doesn't compile. The diffz commit I am depending on is 4792861d6d423f6a8fead9db6c7f0b0024b22136  but any other should also work.

<details>

<summary>src/main.zig</summary>

```zig
const std = @import("std");
const diffz = @import("diffz");
pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const result = try diffz.default.diff(arena.allocator(), "foo", "boor", true);
    std.debug.print("{any}\n", .{result.items});
}
```

</details>

<details>

<summary>build.zig</summary>

```zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const exe = b.addExecutable(.{
        .name = "zig-test",
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.installArtifact(exe);

    const diffz_module = b.dependency("diffz", .{}).module("diffz");
    exe.root_module.addImport("diffz", diffz_module);

    const run_step = b.step("run", "Run main");
    run_step.dependOn(&b.addRunArtifact(exe).step);
}

```

</details>

<details>

<summary>build.zig.zon</summary>

```zig
.{
    .name = "zig-test",
    .version = "0.0.0",
    .dependencies = .{
        // Both of the result in the same hash
        // zig fetch --save git+https://github.com/ziglibs/diffz.git#4792861d6d423f6a8fead9db6c7f0b0024b22136
        // zig fetch --save https://github.com/ziglibs/diffz/archive/4792861d6d423f6a8fead9db6c7f0b0024b22136.tar.gz
        .diffz = .{
            .url = "git+https://github.com/ziglibs/diffz.git#4792861d6d423f6a8fead9db6c7f0b0024b22136",
            .hash = "1220acf95f2b526cf8238ab31aeebb398448c37b45e56530b537aebc5d7beb6715d1",
        },
    },
    .paths = .{"."},
}

```

</details>

<details>

If you were experiencing a hash mismatch error then you compare the hashes of dependencies with `zig fetch --debug-hash URL`

<summary>zig fetch --debug-hash</summary>

Only these 5 files need to exist and match the provided hash in `build.zig.zon`. All other files are filtered out and do not change the hash.

```bash
> zig fetch --debug-hash git+https://github.com/ziglibs/diffz.git#4792861d6d423f6a8fead9db6c7f0b0024b22136
file: 8d1801d14bfd92f9d094485c1f4b88e69f3ff3f0493ace9bd1f9216b0cf6558d: DiffMatchPatch.zig
file: 5a8291845ff2bfeef5134d7e73be726facca9d62b4be94bbd4677e3668ae0177: LICENSE
file: fccbc1f2528c298081b4a01d1387694be0f746ce463e86eafa84c2521e399d75: README.md
file: 4735f1724f564bfbc562e6888cf79b7975f4f37cf2125f89d6a4fd19035510a5: build.zig
file: 20edf3a874b5afdae3aa7f1724b9916c25d28de0f4bbf725b37d4d6d3c8ad545: build.zig.zon
1220acf95f2b526cf8238ab31aeebb398448c37b45e56530b537aebc5d7beb6715d
```

</details>

File: DiffMatchPatch.zig [hunk 7]
```diff
@@ -360,12 +474,20 @@ fn diffHalfMatchInternal(
...
     }
     if (best_common.items.len * 2 >= long_text.len) {
+        const prefix_before = try allocator.dupe(u8, best_long_text_a);
+        errdefer allocator.free(prefix_before);
+        const suffix_before = try allocator.dupe(u8, best_long_text_b);
+        errdefer allocator.free(suffix_before);
+        const prefix_after = try allocator.dupe(u8, best_short_text_a);
+        errdefer allocator.free(prefix_after);
+        const suffix_after = try allocator.dupe(u8, best_short_text_b);
+        const best_common_text = try best_common.toOwnedSlice(allocator);
```
Comment (Techatrix) [inline DiffMatchPatch.zig]:
```suggestion
        const suffix_after = try allocator.dupe(u8, best_short_text_b);
        errdefer allocator.free(suffix_after);
        const best_common_text = try best_common.toOwnedSlice(allocator);
        errdefer allocator.free(best_common_text );
```
The last `errdefer` is technically necessary but it make the code safer to move around. If another field gets added for example, it would be more likely to forget adding back the `errdefer`.

As far as i know, Zig will not analyze for the last `errdefer` so this doesn't affect the generate code.

File: DiffMatchPatch.zig [hunk 8]
```diff
@@ -587,28 +726,31 @@ fn diffLineMode(
...
                 if (count_delete >= 1 and count_insert >= 1) {
                     // Delete the offending records and add the merged ones.
-                    // diffs.RemoveRange(pointer - count_delete - count_insert, count_delete + count_insert);
+                    freeRangeDiffList(
+                        allocator,
+                        &diffs,
+                        pointer - count_delete - count_insert,
+                        count_delete + count_insert,
+                    );
                     try diffs.replaceRange(
```
Comment (Techatrix) [inline DiffMatchPatch.zig]: replacing a range with zero elements will never fail. This should call `replaceRangeAssumeCapacity` instead. If this function would actually return an error then a double free would likely occur.

There are few other `replaceRange` calls that would also be eligible for this change.

File: DiffMatchPatch.zig [hunk 9]
```diff
@@ -1208,15 +1364,12 @@ fn diffCleanupSemanticScore(one: []const u8, two: []const u8) usize {
...
-// Define some regex patterns for matching boundaries.
-// private Regex BLANKLINEEND = new Regex("\\n\\r?\\n\\Z");
-// \n\n
-// \n\r\n
-// private Regex BLANKLINESTART = new Regex("\\A\\r?\\n\\r?\\n");
-// \n\n
-// \r\n\n
-// \n\r\n
-// \r\n\r\n
+inline fn boolInt(b: bool) usize {
```
Comment (Techatrix) [inline DiffMatchPatch.zig]: https://ziglang.org/documentation/0.13.0/#intFromBool

File: DiffMatchPatch.zig [hunk 10]
```diff
@@ -255,6 +344,16 @@ const HalfMatchResult = struct {
     prefix_after: []const u8,
     suffix_after: []const u8,
     common_middle: []const u8,
+
+    // TODO maybe check for empty slice here for fewer copies,
+    // as in, maybe we can transfer ownership and replace with "".
```
Comment (Techatrix) [inline DiffMatchPatch.zig]: Could you explain what this comment is about? fewer copies of the slices or the memory that the slice points to?

File: DiffMatchPatch.zig (hunk 7 above)
Comment (Techatrix) [reply DiffMatchPatch.zig]: Also, is it even necessary to always return a copy of the memory? All slices except `best_common` appear to be substrings of the `long_text` or `short_text`. The caller of `diffHalfMatchInternal` can then decide whether they want to dupe. How exactly each functions handles ownership of the returned function should ideally be documentation in the doc comments of the function. A comment like "caller owns the returned memory" would suffice in most cases.

This change isn't really necessary but a possible optimization to reduce memory usage.

File: DiffMatchPatch.zig [hunk 11]
```diff
@@ -675,11 +824,11 @@ fn diffLinesToCharsMunge(
 ) DiffError![]const u8 {
     var line_start: isize = 0;
     var line_end: isize = -1;
-    var line: []const u8 = "";
+    var line: []const u8 = undefined;
```
Comment (Techatrix) [inline DiffMatchPatch.zig]: nit: initializing with `undefined` can often be avoided by moving the variable to where it is first initialized.

File: DiffMatchPatch.zig [hunk 12]
```diff
@@ -2,9 +2,32 @@ const DiffMatchPatch = @This();
 
 const std = @import("std");
 const testing = std.testing;
+const Allocator = std.mem.Allocator;
 const ArrayListUnmanaged = std.ArrayListUnmanaged;
 const DiffList = ArrayListUnmanaged(Diff);
 
+/// Deinit an `ArrayListUnmanaged(Diff)` and the allocated slices of
+/// text in each `Diff`.
+pub fn deinitDiffList(allocator: Allocator, diffs: *DiffList) void {
```
Comment (Techatrix) [inline DiffMatchPatch.zig]: nit: this function should probably be moved after the `diff` function. The `diff` function should also document that the return value needs to be de allocated with this function.

File: DiffMatchPatch.zig [hunk 13]
```diff
@@ -2,9 +2,32 @@ const DiffMatchPatch = @This();
...
+    defer diffs.deinit(allocator);
+    for (diffs.items) |d| {
+        allocator.free(d.text);
+    }
+}
+
+fn freeRangeDiffList(
```
Comment (Techatrix) [inline DiffMatchPatch.zig]: nit: this function should be moved after the public function. best to show the most important public functions first in a file.

File: DiffMatchPatch.zig [hunk 14]
```diff
@@ -2,9 +2,32 @@ const DiffMatchPatch = @This();
...
+    allocator: Allocator,
+    diffs: *DiffList,
+    start: usize,
+    len: usize,
+) void {
+    const after_range = start + len;
+    const range = diffs.items[start..after_range];
```
Comment (Techatrix) [inline DiffMatchPatch.zig]: nit: Zig has a special syntax to slice-by-length.
```suggestion
    const range = diffs.items[start..][0..len];
```

File: build.zig [hunk 15]
```diff
@@ -1,7 +1,38 @@
...
+        "kcov",
+        "--clean",
+        "--include-pattern=DiffMatchPatch.zig",
+        "--exclude-line=unreachable,expect(false)",
+        "kcov-output",
     });
+    cov_run.addArtifactArg(tests);
+    cov_step.dependOn(&cov_run.step);
+    _ = cov_run.captureStdOut();
+    _ = cov_run.captureStdErr();
```
Comment (Techatrix) [inline build.zig]: The Zig Build System provides functions to declare input and output parameters that will properly deal with caching and dependencies between build steps.
This also avoids the addition of `kcov-output` in the `.gitignore`. The coverage will be stored in `zig-out/coverage`.

I currently can't test this code so there may be some error in it. Shouldn't be a problem since I know it worked for a different project I work on https://github.com/zigtools/zig-lsp-codegen/blob/478d5833cfbc7701bd369a0dd0a53c86b52cbd14/build.zig#L84

```suggestion
    const addOutputDirectoryArg = comptime if (@import("builtin").zig_version.order(.{ .major = 0, .minor = 13, .patch = 0 }) == .lt)
        std.Build.Step.Run.addOutputFileArg
    else
        std.Build.Step.Run.addOutputDirectoryArg;

    const run_kcov = b.addSystemCommand(&.{
        "kcov",
        "--clean",
        "--exclude-line=unreachable,expect(false)",
    });
    run_kcov.addPrefixedDirectoryArg("--include-pattern=", b.path("."));
    const coverage_output = addOutputDirectoryArg(run_kcov, ".");
    run_kcov.addArtifactArg(tests);
    run_kcov.enableTestRunnerMode();

    const install_coverage = b.addInstallDirectory(.{
        .source_dir = coverage_output,
        .install_dir = .{ .custom = "coverage" },
        .install_subdir = "",
    });

    const coverage_step = b.step("coverage", "Generate coverage (kcov must be installed)");
    coverage_step.dependOn(&install_coverage.step);
```

The `addOutputDirectoryArg` has a check to not break compatibility with Zig 0.12.0

**Review by Techatrix — CHANGES_REQUESTED** [review]

File: build.zig (hunk 15 above)
Comment (mnemnion) [reply build.zig]: I'll give it a try and let you know. 

Actually while I'm thinking about it, could you bake this into a patch? That way we don't have to back out the change if something happens. Thanks.

It would be nice if there were a "copy this to clipboard as patch" button but GitHub has never liked patches much.

File: DiffMatchPatch.zig (hunk 10 above)
Comment (mnemnion) [reply DiffMatchPatch.zig]: Sure, everything in a `half_match` struct is fresh text that we just copied, but the fate of that text is somewhat complex. 

You pointed out that a null slice is safe to free as often as you want, so part of that comment is misleading, the `deinit` code wouldn't have to check for `""`. 

I'll see about taking a pass at replacing lines which get copied over with a null slice, instead of copying them a second time.

File: DiffMatchPatch.zig (hunk 11 above)
Comment (mnemnion) [reply DiffMatchPatch.zig]: Like most of the file, that's a straight translation from the C#.

I agree that putting the variable inside the `while` loop is better style.

File: DiffMatchPatch.zig (hunk 12 above)
Comment (mnemnion) [reply DiffMatchPatch.zig]: I'll do that. I have some ideas about making the interface more Zig-ish but that can wait.

Comment (mnemnion) [reply DiffMatchPatch.zig]: So, thought here: should the `DiffList` be moved under `diff` as well, then? Because it's good to keep functions next to the structure they apply to

Comment (mnemnion) [reply DiffMatchPatch.zig]: Ended up keeping them together.

File: DiffMatchPatch.zig (hunk 7 above)
Comment (mnemnion) [reply DiffMatchPatch.zig]: I'm not opposed to taking a crack at further optimization at some later point.

File: DiffMatchPatch.zig (hunk 9 above)
Comment (mnemnion) [reply DiffMatchPatch.zig]: This won't work because the returned value is a `u1`, which causes overflow when two `true` values are added together.

Comment (Techatrix) [reply DiffMatchPatch.zig]: https://ziglang.org/documentation/0.13.0/#as

File: DiffMatchPatch.zig (hunk 8 above)
Comment (mnemnion) [reply DiffMatchPatch.zig]: Done but like. You'd think that ArrayLists would have a better way to spell `deleteRange` than `replaceRangeAssumeCapacity`...

Comment (mnemnion) [reply DiffMatchPatch.zig]: There's 26 letters in there. Even with the gutter at 100 that's a quarter of a line. Anyway. Separate issue.

File: DiffMatchPatch.zig [hunk 16]
```diff
@@ -1208,15 +1365,12 @@ fn diffCleanupSemanticScore(one: []const u8, two: []const u8) usize {
...
-// \n\n
-// \r\n\n
-// \n\r\n
-// \r\n\r\n
+inline fn boolInt(b: bool) usize {
+    if (b)
+        return 1
+    else
+        return 0;
+}
```
Comment (archaistvolts) [inline DiffMatchPatch.zig]: I would write like this.  
```zig
fn boolInt(b: bool) u8 {
    return @intFromBool(b);
}
```
This is the same as writing `@as(u8, @intFromBool(b))`

**Comment by archaistvolts** [comment]
I've just pulled the latest changes from this branch and am test driving.  Didn't notice any issues since yesterday.

File: DiffMatchPatch.zig (hunk 16 above)
Comment (mnemnion) [reply DiffMatchPatch.zig]: I'd guess that the compiler would emit the same code either way, but yeah that's cleaner.

Comment (archaistvolts) [reply DiffMatchPatch.zig]: Yes code is the same in all modes except Debug: https://godbolt.org/z/ovvP6nen7

File: build.zig (hunk 15 above)
Comment (Techatrix) [reply build.zig]: Does GitHub not offer you to commit this patch? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes

Comment (Techatrix) [reply build.zig]: https://github.com/mnemnion/diffz/pull/2

Comment (mnemnion) [reply build.zig]: I'll just go ahead and do that, sure. I was going to make a side branch and check that it works out there, but there's not a lot of advantage in doing so.

File: DiffMatchPatch.zig (hunk 10 above)
Comment (mnemnion) [reply DiffMatchPatch.zig]: Yep, works fine, once I realized the step was now named coverage (which is a good change).

**Comment by mnemnion** [comment]
Added `checkAllFailingAllocations` test for `diffLineMode` which, yes, smoked out some bugs. 

Running this test takes an extraordinarily long time, because the nature of the algorithm is a bunch of tiny allocations, and no obvious way to batch them, and the exhaustive test function is quadratic by the number of allocations. 

It triggers line mode through the "front door" so to speak, and can no doubt be replaced with something shorter which calls `diffLineMode` directly. 

Remaining un-covered lines are little things like the Diff format string, and some errdefers which I don't think are triggerable.  But I'd rather have a few red lines in kcov than be wrong about that.

**Comment by mnemnion** [comment]
Added a field which configures the line-check threshold, using that and truncating the test data gets the allocation failure test down to something comparable to the other tests.

That's probably going to be my last tweak to this branch.
